repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        name: Ruff Linting
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
        name: Ruff Code Formatter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: Static Type Checking (mypy)
        additional_dependencies:
          - pydantic>=1.10.0,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0
          - types-cachetools==5.3.0.5
  
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.3
    hooks:
      - id: uv-lock
        name: Ensure uv.lock Is Up-To-Date

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Spell Checker (codespell)
        args: ["--ignore-words=.codespell-ignore"]
